### ISSUE TITLE
Sharp lines on zoomed in pixels

### ISSUE THREAD

**Issue by josiahseaman** [josiahseaman/DDV#3]
In DNASkittle, we were able to find something like a CSS setting on the image to make sure that pixel boundaries were not blurred.  See if OpenSeaDragon will let us do something similar for sharp lines, or can we set CSS on the element and have it apply?

This is particularly relevant for intMagnification = 1; on large genomes.  It's a 4x performance improvement on server load if we can pull this off.

**Comment by BryanHurst** [comment]
Fixed in 04c88f36
