### ISSUE TITLE
Bug: Nucleotide Number mouse over doesn't make sense in some contexts

### ISSUE THREAD

**Issue by josiahseaman** [josiahseaman/DDV#39]
Using file coordinates is fine for the backend but what is displayed to the user should actually be `Chr 12: 253,404`.  That means including the name of each series as well as its dimensions.  This is useful in a wide range of cases that are poorly supported right now, most of all is Multiple Sequence Alignment, where we'd be able to list off the species and gene name for each row, where that won't fit into the image.  This would also be a decent way of doing mouse over tooltips.  Other applications include clarifying the reference and query columns for whole genome alignments.

Not actually supported in:
- [x] Parallel layout (could be better)
- [x] Multiple Sequence Alignment
- [ ] Transposon layout
- [ ] Gapped parallel could have two valid coordinates (gapped and ungapped index)

**Comment by photomedia** [comment]
this is a crucial navigational feature, so if at all possible, I would recommend keeping it.
