### ISSUE TITLE
NucleotideNumber is showing even when pointing to label

### ISSUE THREAD

**Issue by photomedia** [josiahseaman/DDV#66]
A nucleotide number coordinate is showing even when the user is pointing at a label in a Multi Part Fasta file visualization.

For example, this one: https://dnaskittle.com/ddvresults/dnadata/Human%20selenoproteins/

When user points at SPG000000002, the nucleotide number should display as "-", meaning, not pointing at sequence, but pointing at padding or label.  It currently shows a number (750,589)

**Comment by josiahseaman** [comment]
The number shown is the file position of the beginning of the label.  It's a useful number to have, particularly on the back end.  But I suspect it may end up hidden when we're done with this feature set.
