### ISSUE TITLE
Python 3.7+ issue with `os` import of `errno`

### ISSUE THREAD

**Issue by aganezov** [josiahseaman/DDV#93]
On python version 3.7, 3.8 on MacOS, `errno` import from `os` module raises an `ImportError`, which happens when running FluentDNA main example with chr19 fasta input.

**Comment by josiahseaman** [comment]
Thanks for posting this error.  Mac testing has been challenging.  I'll look into this right away.

"Several undocumented internal imports were removed. One example is that os.errno is no longer available; use import errno directly instead. Note that such undocumented internal imports may be removed any time without notice, even in micro version releases." [Docs](https://docs.python.org/3/whatsnew/3.7.html)

Normally I'd expect a deprecation warning, but I guess it's my fault for not having cross-version, cross-platform continuous integration.

**Comment by josiahseaman** [comment]
@aganezov Would you mind testing the same command now from the python-master branch? We're also testing it on the mac 3.7 environment we have here.

`pip install --upgrade git+https://github.com/josiahseaman/DNASkittleUtils`
`pip install --upgrade git+https://github.com/josiahseaman/FluentDNA.git@python-master`

`./fluentdna --fasta="FluentDNA/example_data/Human selenoproteins.fa"`

Thank you so much for pointing this out. Once I'm done testing I'll push the fix to pip and PyPI.

**Comment by josiahseaman** [comment]
*Update:* The same error existed on DNASkittleUtils, so I fixed it and pushed the change to PyPI.  These commands should resolve the issue.

`pip install --upgrade DNASkittleUtils`
`pip install --upgrade git+https://github.com/josiahseaman/FluentDNA.git@python-master`

**Comment by josiahseaman** [comment]
This is now in the latest pip and [Release versions](https://github.com/josiahseaman/FluentDNA/releases).
